# This file was generated by GoReleaser. DO NOT EDIT.
class Mlc < Formula
  desc "Markdown Link Checker."
  homepage "https://github.com/d-tsuji/markdown-link-check"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/d-tsuji/markdown-link-check/releases/download/v0.0.1/mlc_0.0.1_darwin_amd64.zip"
    sha256 "b24ce7c97e3d08c067f8b3f4ebd23ed8c1e63dfb804a781c56d5eee70ea742d5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/d-tsuji/markdown-link-check/releases/download/v0.0.1/mlc_0.0.1_linux_amd64.zip"
      sha256 "bc8b5c962661d6345f317a83e67c7b6bc59b0eaa40692e1c33fd1492690ecc75"
    end
  end

  def install
    bin.install "mlc"
  end

  test do
    system "#{bin}/mlc"
  end
end
