# This file was generated by GoReleaser. DO NOT EDIT.
class Mlc < Formula
  desc "Markdown Link Checker."
  homepage "https://github.com/d-tsuji/markdown-link-check"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/d-tsuji/markdown-link-check/releases/download/v0.0.4/mlc_0.0.4_darwin_amd64.zip"
    sha256 "997d2feac0513723b90dac78055d06ddb6bbfb602632c3f25c0f71ba97aba9ab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/d-tsuji/markdown-link-check/releases/download/v0.0.4/mlc_0.0.4_linux_amd64.zip"
      sha256 "03bc3fe1f1d82485d95690da8b71bbd42a1d9ddd0c38a2843323fe36774e4a3d"
    end
  end

  def install
    bin.install "mlc"
  end

  test do
    system "#{bin}/mlc"
  end
end
